import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import vm from 'node:vm'
const source = readFileSync(new URL('../plugin.js', import.meta.url), 'utf8')
function load() { const atom = value => ({ get: () => value, set: () => undefined }); const context = { atom, PALETTE_AREA: 'palette', COMPOSER_AREAS: { middleware: 'middleware' }, document: { getElementById: () => null, createElement: () => ({}), head: { appendChild: () => undefined } }, host: { state: { profile: { listen: () => undefined } } } }; const code = source.replace(/^import\s+\{[\s\S]*?\}\s+from '@hermes\/plugin-sdk'\r?\n/m, '').replace(/^import .* from 'react'\r?\n/m, '').replace(/^import .* from 'react\/jsx-runtime'\r?\n/m, '').replace('export default {', 'globalThis.plugin = {').concat('\nglobalThis.__protocol = { composeSoul, messagingProtocol };\n'); vm.runInNewContext(code, context); return context }
test('unit: custom SOUL retains its user content and gets the protocol', () => { const soul = load().__protocol.composeSoul({ name: 'ops', title: '', description: '', customSoul: 'Always verify backups.' }); assert.match(soul, /Always verify backups/); assert.match(soul, /Messaging other agents/) })
test('integration: protocol discovers the live roster and documents Inbox bootstrap', () => { const text = load().__protocol.messagingProtocol('ops'); assert.match(text, /hermes profiles list/); assert.match(text, /sessions list/); assert.match(text, /rename.*Agent Inbox/) })
test('regression: a creation-time roster is not embedded in a new SOUL', () => { const soul = load().__protocol.composeSoul({ name: 'ops', title: 'Operator', description: '', roster: [{ name: 'stale-agent' }], customSoul: '' }); assert.doesNotMatch(soul, /stale-agent/); assert.match(soul, /hermes profiles list/) })
test('system: plugin still registers the live mention middleware', () => { const runtime = load(); const entries = []; runtime.plugin.register({ storage: { get: () => null }, register: item => entries.push(item) }); assert.equal(entries.some(item => item.id === 'mention-middleware'), true) })
test('performance: composeSoul remains bounded for 10,000 creations', () => { const compose = load().__protocol.composeSoul; const start = Date.now(); for (let i = 0; i < 10000; i += 1) compose({ name: 'ops', title: '', description: '', customSoul: 'x' }); assert.ok(Date.now() - start < 1000) })